-- MySQL Script generated by MySQL Workbench
-- Wed Jul 28 09:45:18 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `batch`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `batch` ;

CREATE TABLE IF NOT EXISTS `batch` (
  `batch_id` VARCHAR(32) NOT NULL,
  `start_date` DATE NOT NULL,
  `end_date` DATE NULL,
  `batch_title` VARCHAR(45) NULL,
  PRIMARY KEY (`batch_id`),
  UNIQUE INDEX `batch_id_UNIQUE` (`batch_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `note`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `note` ;

CREATE TABLE IF NOT EXISTS `note` (
  `note_id` VARCHAR(32) NOT NULL,
  `note_content` TEXT NOT NULL,
  `technical_score` ENUM('0', '1', '2', '3', '4') NOT NULL DEFAULT 0,
  `week_number` INT NOT NULL DEFAULT 1,
  `batch_id` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`note_id`),
  UNIQUE INDEX `noteID_UNIQUE` (`note_id` ASC) VISIBLE,
  INDEX `fk_note_batch_idx` (`batch_id` ASC) VISIBLE,
  CONSTRAINT `fk_note_batch`
    FOREIGN KEY (`batch_id`)
    REFERENCES `batch` (`batch_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `associate`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `associate` ;

CREATE TABLE IF NOT EXISTS `associate` (
  `associate_id` VARCHAR(32) NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `batch_id` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`associate_id`),
  UNIQUE INDEX `associate_id_UNIQUE` (`associate_id` ASC) VISIBLE,
  INDEX `fk_associate_batch1_idx` (`batch_id` ASC) VISIBLE,
  CONSTRAINT `fk_associate_batch1`
    FOREIGN KEY (`batch_id`)
    REFERENCES `batch` (`batch_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `user` ;

CREATE TABLE IF NOT EXISTS `user` (
  `user_id` VARCHAR(32) NOT NULL,
  `role` ENUM('Trainer', 'QC_Analyst', 'Admin') NOT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `user_batch`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `user_batch` ;

CREATE TABLE IF NOT EXISTS `user_batch` (
  `user_id` VARCHAR(32) NOT NULL,
  `batch_id` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`user_id`, `batch_id`),
  INDEX `fk_user_has_batch_batch1_idx` (`batch_id` ASC) VISIBLE,
  INDEX `fk_user_has_batch_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_has_batch_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_batch_batch1`
    FOREIGN KEY (`batch_id`)
    REFERENCES `batch` (`batch_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
