/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-1",
    "aws_cognito_region": "us-west-1",
    "aws_user_pools_id": "us-west-1_qGDZLdIL2",
    "aws_user_pools_web_client_id": "6off4bg4opc9i4rhq3kkcfnsr8",
    "oauth": {}
};


export default awsmobile;
